name = "form-handler-worker"
main = "src/index.js"
compatibility_date = "2024-01-15"

# Worker configuration
[build]
command = ""

# Environment variables (set these in Cloudflare dashboard or via wrangler)
[vars]
# These will be overridden by environment-specific vars
ENVIRONMENT = "development"

# Production environment
[env.production]
name = "form-handler-prod"
compatibility_date = "2024-01-15"

# Staging environment  
[env.staging]
name = "form-handler-staging"
compatibility_date = "2024-01-15"

# Development environment
[env.development]
name = "form-handler-dev"
compatibility_date = "2024-01-15"

# KV namespace for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMITER"
id = "your_kv_namespace_id_here"
preview_id = "your_preview_kv_namespace_id_here"
